name = "orange-meets"

account_id = "c145c1bd5046a6996b5cde57e1c962c2"
main = "./build/index.js"
route = { pattern = "meet.inglesconliza.com/*", zone_name = "inglesconliza.com" }
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-10-07"
compatibility_flags = ["nodejs_compat"]

[site]
  bucket = "./public"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[[durable_objects.bindings]]
name = "rooms"
class_name = "ChatRoom"

[vars]
CALLS_APP_ID = "339e4152dc107967bb1ea1ec7d7f469d"
TURN_SERVICE_ID = "46711d6c5759085dd70f599f6190ab94"
EXPERIMENTAL_SIMULCAST_ENABLED = "false"

# Indicate that you want the ChatRoom class to be callable as a Durable Object.
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["ChatRoom"]

[observability]
enabled = true

# The necessary secrets are:
# - CALLS_APP_SECRET
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
